version: 2

jobs:
  one:
    docker:
      - image: circleci/php:7.1-node-browsers
    steps:
      - checkout
      - run: sudo apt install -y libsqlite3-dev zlib1g-dev
workflows:
  version: 2
  phptest:
    jobs:
      - one
